/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RANGGA
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblperintah = new javax.swing.JLabel();
        cbBold = new javax.swing.JCheckBox();
        cbItalic = new javax.swing.JCheckBox();
        cbPerbesar = new javax.swing.JCheckBox();
        lbltext = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuexit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblperintah.setText("ubah huruf");

        cbBold.setText("bold");
        cbBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoldActionPerformed(evt);
            }
        });

        cbItalic.setText("italic");

        cbPerbesar.setText("perbesar");

        lbltext.setText("text ini akan berubah");

        menufile.setText("File");
        menufile.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                menufileMenuKeyTyped(evt);
            }
        });

        jMenu3.setText("menu");
        menufile.add(jMenu3);

        jMenuBar1.add(menufile);

        menuexit.setText("Exit");
        menuexit.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
                menuexitMenuDragMouseExited(evt);
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });
        jMenuBar1.add(menuexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblperintah)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbItalic)
                    .addComponent(cbPerbesar)
                    .addComponent(cbBold))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblperintah)
                    .addComponent(cbBold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbItalic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPerbesar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoldActionPerformed
  
        private void getStyle(){
        Font font = null;
        
        if(cbBold.isSelected() && cbItalic.isSelected() && cbBig.isSelected())
            font = new Font("Serif", Font.BOLD + Font.ITALIC,25);
        else if(cbBold.isSelected() && cbItalic.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.ITALIC,14);
        else if(cbBig.isSelected() && cbItalic.isSelected() )
            font = new Font("Serif", Font.PLAIN + Font.ITALIC,25);
        else if(cbBold.isSelected() && cbBig.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.PLAIN,25);
        else if(cbBold.isSelected())
            font = new Font("Serif", Font.BOLD, 14);
        else if(cbItalic.isSelected())
            font = new Font("Serif", Font.ITALIC, 14);
         else if(cbBig.isSelected())
            font = new Font("Serif", Font.PLAIN ,25);
        else
            font = new Font("Serif", Font.PLAIN,14);
        lblText.setFont(font);
    }
private void cbItalicItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        // TODO add your handling code here:
        getStyle();    }                             
//coding untuk event itemStateChanged
private void cbBoldItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
        getStyle();
    }             
private void cbBigItemStateChanged(java.awt.event.ItemEvent evt) {                                       
        // TODO add your handling code here:
         getStyle();    }                                      

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        System.exit(0);
    }                

    }//GEN-LAST:event_cbBoldActionPerformed

    private void menufileMenuKeyTyped(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menufileMenuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_menufileMenuKeyTyped

    private void menuexitMenuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_menuexitMenuDragMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuexitMenuDragMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbBold;
    private javax.swing.JCheckBox cbItalic;
    private javax.swing.JCheckBox cbPerbesar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblperintah;
    private javax.swing.JLabel lbltext;
    private javax.swing.JMenu menuexit;
    private javax.swing.JMenu menufile;
    // End of variables declaration//GEN-END:variables
}
